"""Tests for Gemini audio/video transcription (Issue #147).

litellm / Gemini are mocked in every test except the single
``@pytest.mark.audio`` integration test (default-skipped). The audio path is
Provider-layer: a transcript is GENERATED by an LLM, so these tests assert the
JSON-segment parsing, robustness (retry, truncation, no-speech), size cap,
MIME routing, cost threading, and orchestrator wiring.
"""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

from kagura_memory.exceptions import KaguraIngestError
from kagura_memory.ingest import _audio
from kagura_memory.ingest._audio import (
    AudioUsage,
    audio_format_label,
    detect_audio_mime,
    is_audio_mime,
    transcribe_audio,
)

# ---------------------------------------------------------------------------
# litellm response stubs
# ---------------------------------------------------------------------------


class _Message:
    def __init__(self, content: str) -> None:
        self.content = content


class _Choice:
    def __init__(self, content: str, finish_reason: str | None = None) -> None:
        self.message = _Message(content)
        self.finish_reason = finish_reason


class _Usage:
    def __init__(self, prompt: int, completion: int) -> None:
        self.prompt_tokens = prompt
        self.completion_tokens = completion


class _Response:
    def __init__(
        self,
        content: str,
        *,
        prompt: int = 1000,
        completion: int = 200,
        finish_reason: str | None = None,
    ) -> None:
        self.choices = [_Choice(content, finish_reason)]
        self.usage = _Usage(prompt, completion)


def _segments_json(segments: list[dict[str, Any]]) -> str:
    return json.dumps({"segments": segments})


_GOOD_JSON = _segments_json(
    [
        {"start": 0.0, "end": 3.5, "text": "Hello and welcome to the talk."},
        {"start": 3.5, "end": 8.0, "text": "Today we discuss audio transcription."},
        {"start": 65.0, "end": 70.0, "text": "An hour-ish in we wrap up."},
    ]
)


def _mock_litellm(response: Any | list[Any]) -> AsyncMock:
    """Build a stand-in litellm module whose acompletion returns ``response``.

    If ``response`` is a list, successive calls pop from it (for retry tests).
    """
    mod = AsyncMock()
    if isinstance(response, list):
        mod.acompletion = AsyncMock(side_effect=response)
    else:
        mod.acompletion = AsyncMock(return_value=response)
    return mod


# ---------------------------------------------------------------------------
# MIME detection
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("uri", "expected"),
    [
        ("/tmp/talk.mp3", "audio/mpeg"),
        ("/tmp/talk.wav", "audio/wav"),
        ("/tmp/talk.m4a", "audio/mp4"),
        ("/tmp/clip.mp4", "video/mp4"),
        ("https://x.com/a/talk.MP3?token=abc", "audio/mpeg"),
        ("/tmp/report.pdf", None),
        ("/tmp/notes.txt", None),
    ],
)
def test_detect_audio_mime_by_suffix(uri: str, expected: str | None) -> None:
    assert detect_audio_mime(source_uri=uri, body=b"") == expected


def test_detect_audio_mime_by_magic_bytes_mp3_id3() -> None:
    assert detect_audio_mime(source_uri="/tmp/noext", body=b"ID3\x04\x00") == "audio/mpeg"


def test_detect_audio_mime_by_magic_bytes_mp3_sync() -> None:
    assert detect_audio_mime(source_uri="/tmp/noext", body=b"\xff\xfb\x90\x00") == "audio/mpeg"


def test_detect_audio_mime_by_magic_bytes_wav() -> None:
    body = b"RIFF\x24\x08\x00\x00WAVEfmt "
    assert detect_audio_mime(source_uri="/tmp/noext", body=body) == "audio/wav"


def test_detect_audio_mime_by_magic_bytes_m4a() -> None:
    body = b"\x00\x00\x00\x20ftypM4A \x00\x00\x00\x00"
    assert detect_audio_mime(source_uri="/tmp/noext", body=body) == "audio/mp4"


def test_detect_audio_mime_by_magic_bytes_mp4() -> None:
    body = b"\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00"
    assert detect_audio_mime(source_uri="/tmp/noext", body=body) == "video/mp4"


def test_detect_audio_mime_non_audio_returns_none() -> None:
    assert detect_audio_mime(source_uri="/tmp/x", body=b"%PDF-1.7 not audio") is None


def test_detect_audio_mime_by_content_type_when_suffix_and_magic_miss() -> None:
    # No audio suffix and non-audio magic bytes, but a registered audio
    # Content-Type — the Content-Type must win (server is authoritative).
    assert (
        detect_audio_mime(
            source_uri="https://cdn.example/stream?id=42",
            body=b"not-a-recognized-magic-prefix",
            content_type="audio/mpeg",
        )
        == "audio/mpeg"
    )


def test_detect_audio_mime_content_type_wins_over_non_audio_suffix() -> None:
    # A registered audio Content-Type takes precedence over a non-audio
    # filename suffix (e.g. an extension-less download endpoint named *.bin).
    assert (
        detect_audio_mime(
            source_uri="https://cdn.example/download.bin",
            body=b"",
            content_type="audio/mp4; codecs=mp4a.40.2",
        )
        == "audio/mp4"
    )


def test_detect_audio_mime_content_type_video_recognized() -> None:
    assert (
        detect_audio_mime(source_uri="/tmp/clip", body=b"", content_type="video/mp4") == "video/mp4"
    )


def test_detect_audio_mime_generic_content_type_falls_back_to_suffix() -> None:
    # A GENERIC Content-Type (octet-stream) is "I don't know", so suffix
    # detection still applies (a real .mp3 mislabeled by the server).
    assert (
        detect_audio_mime(
            source_uri="/tmp/talk.mp3",
            body=b"",
            content_type="application/octet-stream",
        )
        == "audio/mpeg"
    )


def test_detect_audio_mime_concrete_non_audio_content_type_blocks_suffix() -> None:
    # A CONCRETE non-audio Content-Type (e.g. text/html for a login/redirect
    # page served at a .mp3 URL) is authoritative — it must NOT be audio-routed
    # on the misleading suffix, so the bytes never reach Gemini.
    assert (
        detect_audio_mime(
            source_uri="https://evil.example/login.mp3",
            body=b"<!doctype html>",
            content_type="text/html; charset=utf-8",
        )
        is None
    )


def test_detect_audio_mime_audio_alias_content_type_falls_back_to_suffix() -> None:
    # An unrecognized audio/* alias (audio/mp3, audio/wave) is NOT "something
    # else" — it must fall through to suffix/magic so a real MP3/WAV routes.
    assert (
        detect_audio_mime(source_uri="/tmp/talk.mp3", body=b"", content_type="audio/mp3")
        == "audio/mpeg"
    )
    assert (
        detect_audio_mime(source_uri="/tmp/talk.wav", body=b"", content_type="audio/wave")
        == "audio/wav"
    )


def test_detect_audio_mime_rejects_non_av_ftyp_brands() -> None:
    # AVIF / HEIC images are ISO-BMFF with an "ftyp" box too — they must NOT be
    # routed to transcription. Only known MP4/M4A brands match.
    avif = b"\x00\x00\x00\x20ftypavif\x00\x00\x00\x00"
    heic = b"\x00\x00\x00\x18ftypheic\x00\x00\x00\x00"
    assert detect_audio_mime(source_uri="/tmp/img", body=avif) is None
    assert detect_audio_mime(source_uri="/tmp/img", body=heic) is None


def test_is_audio_mime() -> None:
    assert is_audio_mime("audio/mpeg") is True
    assert is_audio_mime("video/mp4") is True
    assert is_audio_mime("audio/mpeg; codecs=x".replace("mpeg", "mpeg")) is True
    assert is_audio_mime("application/pdf") is False
    assert is_audio_mime(None) is False


def test_audio_format_label() -> None:
    assert audio_format_label("audio/mpeg") == "audio"
    assert audio_format_label("video/mp4") == "video"


# ---------------------------------------------------------------------------
# transcribe_audio — happy path
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_transcribe_happy_path_builds_time_windowed_sections() -> None:
    mod = _mock_litellm(_Response(_GOOD_JSON, prompt=4096, completion=300))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, usage = await transcribe_audio(
            b"\x00fakeaudio", mime="audio/mpeg", source_uri="/data/talk.mp3"
        )

    assert content.title == "talk.mp3"
    assert content.page_count is None
    assert len(content.sections) == 3
    # Headings are mm:ss timestamps; the > 1h-ish one stays mm:ss until 3600s.
    assert content.sections[0].heading == "[00:00]"
    assert content.sections[0].anchor == "00:00-00:03"
    assert content.sections[0].body_text == "Hello and welcome to the talk."
    assert content.sections[1].heading == "[00:03]"
    assert content.sections[2].heading == "[01:05]"
    assert content.sections[2].anchor == "01:05-01:10"
    # Provider-reported usage threaded out for CostBreakdown.
    assert usage.prompt_tokens == 4096
    assert usage.completion_tokens == 300

    # The audio bytes were attached inline as base64 data-url.
    call = mod.acompletion.call_args
    messages = call.kwargs["messages"]
    parts = messages[1]["content"]
    data_url = next(p["image_url"]["url"] for p in parts if p["type"] == "image_url")
    assert data_url.startswith("data:audio/mpeg;base64,")
    assert base64.b64encode(b"\x00fakeaudio").decode() in data_url
    assert call.kwargs["response_format"] == {"type": "json_object"}


@pytest.mark.asyncio
async def test_transcribe_accepts_bare_list_json() -> None:
    raw = json.dumps([{"start": 0, "end": 1, "text": "hi"}])
    mod = _mock_litellm(_Response(raw))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert len(content.sections) == 1


@pytest.mark.asyncio
async def test_transcribe_strips_markdown_fence() -> None:
    raw = "```json\n" + _segments_json([{"start": 0, "end": 1, "text": "fenced"}]) + "\n```"
    mod = _mock_litellm(_Response(raw))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert content.sections[0].body_text == "fenced"


@pytest.mark.asyncio
async def test_transcribe_skips_junk_segments() -> None:
    raw = _segments_json(
        [
            {"start": 0, "end": 1, "text": "good"},
            {"start": "bad", "end": 2, "text": "dropped"},  # non-numeric start
            {"start": 2, "end": 3},  # missing text
            {"start": 3, "end": 4, "text": "   "},  # empty text
            {"start": 4, "end": 5, "text": "alsogood"},
        ]
    )
    mod = _mock_litellm(_Response(raw))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert [s.body_text for s in content.sections] == ["good", "alsogood"]


# ---------------------------------------------------------------------------
# Robustness — malformed / truncated / no-speech / oversized
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_malformed_json_raises_after_retry() -> None:
    bad = _Response("this is not json at all")
    mod = _mock_litellm([bad, bad])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    # Exactly one retry → two provider calls.
    assert mod.acompletion.await_count == 2


@pytest.mark.asyncio
async def test_truncated_json_raises() -> None:
    truncated = _Response('{"segments": [{"start": 0, "end": 1, "text": "incompl')
    mod = _mock_litellm([truncated, truncated])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="truncated|could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


@pytest.mark.asyncio
async def test_truncation_by_finish_reason_fails_fast() -> None:
    # Valid, parseable JSON but the model hit its output-token cap
    # (finish_reason="length"): the transcript is silently incomplete. Detect it
    # and fail fast — an identical retry would just truncate again and re-bill.
    truncated = _Response(_GOOD_JSON, finish_reason="length")
    mod = _mock_litellm([truncated, truncated])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="truncated"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    # No retry on deterministic truncation: exactly one provider call.
    assert mod.acompletion.await_count == 1


@pytest.mark.asyncio
async def test_retry_recovers_after_first_bad_response() -> None:
    bad = _Response("nonsense")
    good = _Response(_segments_json([{"start": 0, "end": 1, "text": "recovered"}]))
    mod = _mock_litellm([bad, good])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert content.sections[0].body_text == "recovered"
    assert mod.acompletion.await_count == 2


@pytest.mark.asyncio
async def test_retry_accumulates_usage_across_attempts() -> None:
    # Both the malformed first call and the successful retry are billable —
    # reported usage must be the SUM, not just the recovery attempt's.
    bad = _Response("nonsense", prompt=900, completion=10)
    good = _Response(
        _segments_json([{"start": 0, "end": 1, "text": "ok"}]), prompt=1100, completion=50
    )
    mod = _mock_litellm([bad, good])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        _, usage = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert usage.prompt_tokens == 2000  # 900 + 1100
    assert usage.completion_tokens == 60  # 10 + 50


@pytest.mark.asyncio
async def test_non_finite_segment_raises_clean_ingest_error() -> None:
    """NaN/Infinity literals in the model JSON must surface as KaguraIngestError.

    json.loads accepts NaN/Infinity/-Infinity by default; left unchecked those
    floats reach _format_timestamp where int(float('nan'))/int(float('inf'))
    raises a raw ValueError/OverflowError. We reject them as a parse error
    (one retry, then a clean KaguraIngestError — never a raw ValueError).
    """
    bad = _Response('{"segments": [{"start": NaN, "end": Infinity, "text": "hi"}]}')
    mod = _mock_litellm([bad, bad])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert mod.acompletion.await_count == 2


def test_reject_non_finite_raises_parse_error() -> None:
    with pytest.raises(_audio._TranscriptParseError, match="non-finite"):
        _audio._reject_non_finite("NaN")


def test_parse_segments_rejects_non_finite_literals() -> None:
    for token in ("NaN", "Infinity", "-Infinity"):
        with pytest.raises(_audio._TranscriptParseError, match="non-finite"):
            _audio._parse_segments(f'{{"segments": [{{"start": {token}, "end": 1, "text": "x"}}]}}')


def test_as_float_rejects_string_non_finite() -> None:
    # float("inf")/float("nan") succeed, so guard with math.isfinite.
    assert _audio._as_float("inf") is None
    assert _audio._as_float("nan") is None
    assert _audio._as_float("-inf") is None


def test_as_float_rejects_bool_and_non_numeric() -> None:
    assert _audio._as_float(True) is None  # bool is an int subclass — rejected
    assert _audio._as_float(None) is None
    assert _audio._as_float([1, 2]) is None  # non-numeric type
    assert _audio._as_float("1.5") == 1.5


def test_parse_segments_empty_response_raises() -> None:
    with pytest.raises(_audio._TranscriptParseError, match="empty response"):
        _audio._parse_segments("   ")


def test_parse_segments_non_object_or_list_raises() -> None:
    with pytest.raises(_audio._TranscriptParseError, match="not an object or list"):
        _audio._parse_segments("42")


def test_parse_segments_segments_not_a_list_raises() -> None:
    with pytest.raises(_audio._TranscriptParseError, match="not a list"):
        _audio._parse_segments('{"segments": {"start": 0}}')


def test_parse_segments_skips_non_dict_items() -> None:
    segs = _audio._parse_segments('{"segments": ["junk", {"start": 0, "end": 1, "text": "ok"}]}')
    assert [s.text for s in segs] == ["ok"]


def test_parse_segments_missing_segments_field_raises() -> None:
    # A dict that OMITS the required "segments" key is a malformed response,
    # not silence — it must raise (→ one-shot retry) rather than be silently
    # treated as an empty/no-speech result.
    with pytest.raises(_audio._TranscriptParseError, match="missing the 'segments'"):
        _audio._parse_segments('{"foo": "bar"}')


def test_parse_segments_explicit_empty_segments_is_no_speech() -> None:
    # An explicit empty list IS the no-speech contract — a valid parse that
    # yields zero segments (transcribe_audio then raises the no-speech error).
    assert _audio._parse_segments('{"segments": []}') == []


def test_parse_segments_all_invalid_items_raises() -> None:
    # A non-empty segments list that yields zero VALID segments is malformed
    # (not silence) → raise so the one-shot retry fires.
    with pytest.raises(_audio._TranscriptParseError, match="no valid"):
        _audio._parse_segments('{"segments": ["junk", {"start": 0}, {"text": "x"}]}')


@pytest.mark.asyncio
async def test_all_invalid_segments_retries_then_raises() -> None:
    # End-to-end: a {"segments": [<all invalid>]} response is malformed → retry
    # → clean KaguraIngestError, not the no-speech path.
    bad = _Response('{"segments": [{"start": 0}, "junk"]}')
    mod = _mock_litellm([bad, bad])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert mod.acompletion.await_count == 2


@pytest.mark.asyncio
async def test_missing_segments_field_retries_then_raises() -> None:
    # End-to-end: a response missing "segments" is malformed → retry → clean
    # KaguraIngestError (not the no-speech message, and not a raw error).
    bad = _Response('{"foo": "bar"}')
    mod = _mock_litellm([bad, bad])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert mod.acompletion.await_count == 2


def test_parse_segments_clamps_end_before_start() -> None:
    segs = _audio._parse_segments('{"segments": [{"start": 5, "end": 2, "text": "x"}]}')
    assert segs[0].start == 5.0
    assert segs[0].end == 5.0  # end < start clamped to start


def test_extract_content_handles_bad_response() -> None:
    assert _audio._extract_content(object()) == ""  # no .choices → AttributeError path


def test_extract_usage_handles_non_int_tokens() -> None:
    class _BadUsage:
        prompt_tokens = "oops"  # int() raises ValueError → defaults to zeros
        completion_tokens = 5

    class _Resp:
        usage = _BadUsage()

    usage = _audio._extract_usage(_Resp(), model="m")
    assert usage.prompt_tokens == 0
    assert usage.completion_tokens == 0
    assert usage.model == "m"


def test_format_timestamp_past_one_hour() -> None:
    assert _audio._format_timestamp(3725.0) == "1:02:05"  # hh:mm:ss branch


def test_load_litellm_returns_module_when_installed() -> None:
    # litellm IS installed here, so the real lazy loader reaches its success
    # line and returns the module (covers the non-error import path).
    assert _audio._load_litellm() is not None


@pytest.mark.asyncio
async def test_no_speech_empty_segments_raises_actionable() -> None:
    mod = _mock_litellm(_Response(_segments_json([])))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="no speech|no intelligible"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


@pytest.mark.asyncio
async def test_oversized_file_raises_ffmpeg_followup() -> None:
    # max_bytes_audio=12 → inline_limit = 12 * 4 // 3 = 16 bytes. 100 raw bytes
    # encode to 136 base64 bytes, well over the 16-byte encoded cap → reject.
    mod = _mock_litellm(_Response(_GOOD_JSON))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="ffmpeg"):
            await transcribe_audio(
                b"x" * 100, mime="audio/mpeg", source_uri="big.mp3", max_bytes_audio=12
            )
    mod.acompletion.assert_not_called()  # rejected before any provider call


@pytest.mark.asyncio
async def test_raw_under_cap_but_base64_over_inline_limit_rejected() -> None:
    # The cap is on the ENCODED payload, not the raw bytes. Pick a raw size that
    # is UNDER the raw cap arithmetic would naively allow, but whose base64
    # form exceeds the inline limit. With max_bytes_audio=12 the raw bytes are
    # within 12 only up to 12 bytes; choose 13 raw bytes (just over the raw cap
    # but the point is the *encoded* boundary): encoded = ceil(13/3)*4 = 20 >
    # inline_limit (16) → must reject. A file at the raw cap (12) encodes to 16,
    # exactly the inline limit, and is accepted.
    mod = _mock_litellm(_Response(_GOOD_JSON))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="base64-encoded"):
            await transcribe_audio(
                b"x" * 13, mime="audio/mpeg", source_uri="boundary.mp3", max_bytes_audio=12
            )
    mod.acompletion.assert_not_called()


@pytest.mark.asyncio
async def test_at_encoded_boundary_is_accepted() -> None:
    # Raw size exactly at the cap: encoded == inline_limit → accepted (the
    # boundary is now on the encoded size, not the raw size). max_bytes_audio=12
    # → inline_limit=16; 12 raw bytes encode to ((12+2)//3)*4 = 16 == 16 → ok.
    mod = _mock_litellm(_Response(_GOOD_JSON))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(
            b"x" * 12, mime="audio/mpeg", source_uri="ok.mp3", max_bytes_audio=12
        )
    assert content.sections  # transcription proceeded past the size gate
    mod.acompletion.assert_called_once()


@pytest.mark.asyncio
async def test_provider_call_failure_raises_ingest_error() -> None:
    mod = AsyncMock()
    mod.acompletion = AsyncMock(side_effect=RuntimeError("boom"))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="provider call failed"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


@pytest.mark.asyncio
async def test_missing_dep_raises_pointing_at_extra() -> None:
    def _boom() -> Any:
        raise KaguraIngestError(
            "litellm is required for audio/video transcription. Install with: "
            "pip install 'kagura-memory[ingest-audio]'"
        )

    with patch.object(_audio, "_load_litellm", side_effect=_boom):
        with pytest.raises(KaguraIngestError, match=r"ingest-audio"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


def test_load_litellm_importerror_maps_to_ingest_error() -> None:
    import builtins

    real_import = builtins.__import__

    def fake_import(name: str, *args: Any, **kwargs: Any) -> Any:
        if name == "litellm":
            raise ImportError("no litellm")
        return real_import(name, *args, **kwargs)

    with patch.object(builtins, "__import__", side_effect=fake_import):
        with pytest.raises(KaguraIngestError, match="ingest-audio"):
            _audio._load_litellm()


# ---------------------------------------------------------------------------
# Orchestrator wiring
# ---------------------------------------------------------------------------


def _make_client() -> Any:
    from kagura_memory.client import KaguraClient

    client = KaguraClient(api_key="test", mcp_url="https://test.com/mcp")
    client._session_id = "test-session"
    return client


class _FakeProvider:
    name = "fake"
    default_text_model = "fake/text"
    default_vision_model: str | None = None
    text_model = "fake/text"
    vision_model: str | None = None

    async def summarize(self, text: str, *, max_tokens: int, steering: str | None = None) -> str:
        return f"[summary len={len(text)}]"

    async def summarize_overview(
        self, section_summaries: list[str], *, max_tokens: int, steering: str | None = None
    ) -> str:
        return f"[overview {len(section_summaries)}]"

    async def describe_image(self, image_bytes: bytes, mime: str) -> str:
        return "[image]"

    def count_tokens(self, text: str, *, for_vision: bool = False) -> int:
        return max(1, len(text) // 4)


@pytest.mark.asyncio
async def test_ingest_routes_mp3_to_audio_path(tmp_path: Path) -> None:
    from kagura_memory.ingest import FileIngestor

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")

    client = _make_client()
    ingestor = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    counter = {"n": 0}
    captured: list[dict[str, Any]] = []

    async def capture_remember(*, context_id: str, **kwargs: Any) -> dict[str, Any]:
        captured.append({"context_id": context_id, **kwargs})
        counter["n"] += 1
        return {"memory_id": f"mem-{counter['n']}"}

    mod = _mock_litellm(_Response(_GOOD_JSON, prompt=5000, completion=400))
    with (
        patch.object(_audio, "_load_litellm", return_value=mod),
        patch.object(client, "remember", side_effect=capture_remember),
    ):
        result = await ingestor.ingest(str(audio_file), context_id="ctx-uuid")

    assert result.success is True
    assert result.overview_id == "mem-1"
    assert len(result.section_ids) == 3
    # format label routed as audio; cost carries the provider token usage.
    assert captured[0]["details"]["format"] == "audio"
    assert result.cost.prompt_tokens == 5000
    assert result.cost.completion_tokens == 400
    assert result.cost.is_estimate is False

    await client.close()


@pytest.mark.asyncio
async def test_ingest_audio_transcription_failure_records_extract_error(tmp_path: Path) -> None:
    from kagura_memory.ingest import FileIngestor

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")

    client = _make_client()
    ingestor = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    mod = _mock_litellm([_Response("not json"), _Response("still not json")])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        result = await ingestor.ingest(str(audio_file), context_id="ctx-uuid")

    assert result.success is False
    assert result.errors
    assert result.errors[0].step == "extract"
    await client.close()


@pytest.mark.asyncio
async def test_dry_run_audio_does_not_call_provider(tmp_path: Path) -> None:
    from kagura_memory.ingest import FileIngestor

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")

    client = _make_client()
    ingestor = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    mod = _mock_litellm(_Response(_GOOD_JSON))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        result = await ingestor.estimate_cost(str(audio_file))

    assert result.is_dry_run is True
    assert result.cost.is_estimate is True
    mod.acompletion.assert_not_called()  # NO network on dry-run
    assert any("estimate" in w for w in result.warnings)
    await client.close()


def test_audio_inline_oversize_none_for_small_input() -> None:
    assert _audio.audio_inline_oversize_message(b"x" * 100) is None


def test_audio_inline_oversize_caps_at_provider_limit() -> None:
    # Raising max_bytes_audio above Gemini's hard inline limit must NOT let an
    # oversized request through — the effective cap is bounded by the provider.
    big = b"\x00" * (16 * 1024 * 1024)  # ~21.8 MB base64, over the 20 MB hard cap
    assert _audio.audio_inline_oversize_message(big, max_bytes_audio=100 * 1024 * 1024) is not None


@pytest.mark.asyncio
async def test_dry_run_audio_oversize_reports_extract_error(tmp_path: Path) -> None:
    # The dry-run audio branch applies the same size preflight as real ingest,
    # so an oversized file is a step="extract" error, not a "success" estimate.
    from kagura_memory.ingest import FileIngestor
    from kagura_memory.ingest import ingestor as ingestor_mod

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")
    client = _make_client()
    ing = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    with patch.object(
        ingestor_mod, "audio_inline_oversize_message", return_value="too big — ffmpeg follow-up"
    ):
        result = await ing.estimate_cost(str(audio_file))

    assert result.is_dry_run is True
    assert any(e.step == "extract" and "too big" in e.message for e in result.errors)
    await client.close()


# ---------------------------------------------------------------------------
# Integration (default-skipped) — real Gemini transcription
# ---------------------------------------------------------------------------


@pytest.mark.audio
@pytest.mark.asyncio
async def test_real_gemini_transcription() -> None:
    """Requires GEMINI_API_KEY + network. Run with: pytest -m audio."""
    if not os.environ.get("GEMINI_API_KEY"):
        pytest.skip("GEMINI_API_KEY not set")
    fixture = Path(__file__).parent / "fixtures" / "sample.mp3"
    if not fixture.exists():
        pytest.skip("tests/fixtures/sample.mp3 not present")

    content, usage = await transcribe_audio(
        fixture.read_bytes(), mime="audio/mpeg", source_uri=str(fixture)
    )
    assert content.sections
    assert usage.prompt_tokens > 0


def test_audio_usage_defaults() -> None:
    u = AudioUsage()
    assert u.prompt_tokens == 0
    assert u.completion_tokens == 0
    assert u.model is None
