"""Tests for Gemini audio/video transcription (Issue #147).

litellm / Gemini are mocked in every test except the single
``@pytest.mark.audio`` integration test (default-skipped). The audio path is
Provider-layer: a transcript is GENERATED by an LLM, so these tests assert the
JSON-segment parsing, robustness (retry, truncation, no-speech), size cap,
MIME routing, cost threading, and orchestrator wiring.
"""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

from kagura_memory.exceptions import KaguraIngestError
from kagura_memory.ingest import _audio
from kagura_memory.ingest._audio import (
    AudioUsage,
    audio_format_label,
    detect_audio_mime,
    is_audio_mime,
    transcribe_audio,
)

# ---------------------------------------------------------------------------
# litellm response stubs
# ---------------------------------------------------------------------------


class _Message:
    def __init__(self, content: str) -> None:
        self.content = content


class _Choice:
    def __init__(self, content: str) -> None:
        self.message = _Message(content)


class _Usage:
    def __init__(self, prompt: int, completion: int) -> None:
        self.prompt_tokens = prompt
        self.completion_tokens = completion


class _Response:
    def __init__(self, content: str, *, prompt: int = 1000, completion: int = 200) -> None:
        self.choices = [_Choice(content)]
        self.usage = _Usage(prompt, completion)


def _segments_json(segments: list[dict[str, Any]]) -> str:
    return json.dumps({"segments": segments})


_GOOD_JSON = _segments_json(
    [
        {"start": 0.0, "end": 3.5, "text": "Hello and welcome to the talk."},
        {"start": 3.5, "end": 8.0, "text": "Today we discuss audio transcription."},
        {"start": 65.0, "end": 70.0, "text": "An hour-ish in we wrap up."},
    ]
)


def _mock_litellm(response: Any | list[Any]) -> AsyncMock:
    """Build a stand-in litellm module whose acompletion returns ``response``.

    If ``response`` is a list, successive calls pop from it (for retry tests).
    """
    mod = AsyncMock()
    if isinstance(response, list):
        mod.acompletion = AsyncMock(side_effect=response)
    else:
        mod.acompletion = AsyncMock(return_value=response)
    return mod


# ---------------------------------------------------------------------------
# MIME detection
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("uri", "expected"),
    [
        ("/tmp/talk.mp3", "audio/mpeg"),
        ("/tmp/talk.wav", "audio/wav"),
        ("/tmp/talk.m4a", "audio/mp4"),
        ("/tmp/clip.mp4", "video/mp4"),
        ("https://x.com/a/talk.MP3?token=abc", "audio/mpeg"),
        ("/tmp/report.pdf", None),
        ("/tmp/notes.txt", None),
    ],
)
def test_detect_audio_mime_by_suffix(uri: str, expected: str | None) -> None:
    assert detect_audio_mime(source_uri=uri, body=b"") == expected


def test_detect_audio_mime_by_magic_bytes_mp3_id3() -> None:
    assert detect_audio_mime(source_uri="/tmp/noext", body=b"ID3\x04\x00") == "audio/mpeg"


def test_detect_audio_mime_by_magic_bytes_mp3_sync() -> None:
    assert detect_audio_mime(source_uri="/tmp/noext", body=b"\xff\xfb\x90\x00") == "audio/mpeg"


def test_detect_audio_mime_by_magic_bytes_wav() -> None:
    body = b"RIFF\x24\x08\x00\x00WAVEfmt "
    assert detect_audio_mime(source_uri="/tmp/noext", body=body) == "audio/wav"


def test_detect_audio_mime_by_magic_bytes_m4a() -> None:
    body = b"\x00\x00\x00\x20ftypM4A \x00\x00\x00\x00"
    assert detect_audio_mime(source_uri="/tmp/noext", body=body) == "audio/mp4"


def test_detect_audio_mime_by_magic_bytes_mp4() -> None:
    body = b"\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00"
    assert detect_audio_mime(source_uri="/tmp/noext", body=body) == "video/mp4"


def test_detect_audio_mime_non_audio_returns_none() -> None:
    assert detect_audio_mime(source_uri="/tmp/x", body=b"%PDF-1.7 not audio") is None


def test_is_audio_mime() -> None:
    assert is_audio_mime("audio/mpeg") is True
    assert is_audio_mime("video/mp4") is True
    assert is_audio_mime("audio/mpeg; codecs=x".replace("mpeg", "mpeg")) is True
    assert is_audio_mime("application/pdf") is False
    assert is_audio_mime(None) is False


def test_audio_format_label() -> None:
    assert audio_format_label("audio/mpeg") == "audio"
    assert audio_format_label("video/mp4") == "video"


# ---------------------------------------------------------------------------
# transcribe_audio — happy path
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_transcribe_happy_path_builds_time_windowed_sections() -> None:
    mod = _mock_litellm(_Response(_GOOD_JSON, prompt=4096, completion=300))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, usage = await transcribe_audio(
            b"\x00fakeaudio", mime="audio/mpeg", source_uri="/data/talk.mp3"
        )

    assert content.title == "talk.mp3"
    assert content.page_count is None
    assert len(content.sections) == 3
    # Headings are mm:ss timestamps; the > 1h-ish one stays mm:ss until 3600s.
    assert content.sections[0].heading == "[00:00]"
    assert content.sections[0].anchor == "00:00-00:03"
    assert content.sections[0].body_text == "Hello and welcome to the talk."
    assert content.sections[1].heading == "[00:03]"
    assert content.sections[2].heading == "[01:05]"
    assert content.sections[2].anchor == "01:05-01:10"
    # Provider-reported usage threaded out for CostBreakdown.
    assert usage.prompt_tokens == 4096
    assert usage.completion_tokens == 300

    # The audio bytes were attached inline as base64 data-url.
    call = mod.acompletion.call_args
    messages = call.kwargs["messages"]
    parts = messages[1]["content"]
    data_url = next(p["image_url"]["url"] for p in parts if p["type"] == "image_url")
    assert data_url.startswith("data:audio/mpeg;base64,")
    assert base64.b64encode(b"\x00fakeaudio").decode() in data_url
    assert call.kwargs["response_format"] == {"type": "json_object"}


@pytest.mark.asyncio
async def test_transcribe_accepts_bare_list_json() -> None:
    raw = json.dumps([{"start": 0, "end": 1, "text": "hi"}])
    mod = _mock_litellm(_Response(raw))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert len(content.sections) == 1


@pytest.mark.asyncio
async def test_transcribe_strips_markdown_fence() -> None:
    raw = "```json\n" + _segments_json([{"start": 0, "end": 1, "text": "fenced"}]) + "\n```"
    mod = _mock_litellm(_Response(raw))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert content.sections[0].body_text == "fenced"


@pytest.mark.asyncio
async def test_transcribe_skips_junk_segments() -> None:
    raw = _segments_json(
        [
            {"start": 0, "end": 1, "text": "good"},
            {"start": "bad", "end": 2, "text": "dropped"},  # non-numeric start
            {"start": 2, "end": 3},  # missing text
            {"start": 3, "end": 4, "text": "   "},  # empty text
            {"start": 4, "end": 5, "text": "alsogood"},
        ]
    )
    mod = _mock_litellm(_Response(raw))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert [s.body_text for s in content.sections] == ["good", "alsogood"]


# ---------------------------------------------------------------------------
# Robustness — malformed / truncated / no-speech / oversized
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_malformed_json_raises_after_retry() -> None:
    bad = _Response("this is not json at all")
    mod = _mock_litellm([bad, bad])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    # Exactly one retry → two provider calls.
    assert mod.acompletion.await_count == 2


@pytest.mark.asyncio
async def test_truncated_json_raises() -> None:
    truncated = _Response('{"segments": [{"start": 0, "end": 1, "text": "incompl')
    mod = _mock_litellm([truncated, truncated])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="truncated|could not parse"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


@pytest.mark.asyncio
async def test_retry_recovers_after_first_bad_response() -> None:
    bad = _Response("nonsense")
    good = _Response(_segments_json([{"start": 0, "end": 1, "text": "recovered"}]))
    mod = _mock_litellm([bad, good])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        content, _ = await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")
    assert content.sections[0].body_text == "recovered"
    assert mod.acompletion.await_count == 2


@pytest.mark.asyncio
async def test_no_speech_empty_segments_raises_actionable() -> None:
    mod = _mock_litellm(_Response(_segments_json([])))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="no speech|no intelligible"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


@pytest.mark.asyncio
async def test_oversized_file_raises_ffmpeg_followup() -> None:
    mod = _mock_litellm(_Response(_GOOD_JSON))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="ffmpeg"):
            await transcribe_audio(
                b"x" * 100, mime="audio/mpeg", source_uri="big.mp3", max_bytes_audio=10
            )
    mod.acompletion.assert_not_called()  # rejected before any provider call


@pytest.mark.asyncio
async def test_provider_call_failure_raises_ingest_error() -> None:
    mod = AsyncMock()
    mod.acompletion = AsyncMock(side_effect=RuntimeError("boom"))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        with pytest.raises(KaguraIngestError, match="provider call failed"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


@pytest.mark.asyncio
async def test_missing_dep_raises_pointing_at_extra() -> None:
    def _boom() -> Any:
        raise KaguraIngestError(
            "litellm is required for audio/video transcription. Install with: "
            "pip install 'kagura-memory[ingest-audio]'"
        )

    with patch.object(_audio, "_load_litellm", side_effect=_boom):
        with pytest.raises(KaguraIngestError, match=r"ingest-audio"):
            await transcribe_audio(b"x", mime="audio/mpeg", source_uri="a.mp3")


def test_load_litellm_importerror_maps_to_ingest_error() -> None:
    import builtins

    real_import = builtins.__import__

    def fake_import(name: str, *args: Any, **kwargs: Any) -> Any:
        if name == "litellm":
            raise ImportError("no litellm")
        return real_import(name, *args, **kwargs)

    with patch.object(builtins, "__import__", side_effect=fake_import):
        with pytest.raises(KaguraIngestError, match="ingest-audio"):
            _audio._load_litellm()


# ---------------------------------------------------------------------------
# Orchestrator wiring
# ---------------------------------------------------------------------------


def _make_client() -> Any:
    from kagura_memory.client import KaguraClient

    client = KaguraClient(api_key="test", mcp_url="https://test.com/mcp")
    client._session_id = "test-session"
    return client


class _FakeProvider:
    name = "fake"
    default_text_model = "fake/text"
    default_vision_model: str | None = None
    text_model = "fake/text"
    vision_model: str | None = None

    async def summarize(self, text: str, *, max_tokens: int) -> str:
        return f"[summary len={len(text)}]"

    async def summarize_overview(self, section_summaries: list[str], *, max_tokens: int) -> str:
        return f"[overview {len(section_summaries)}]"

    async def describe_image(self, image_bytes: bytes, mime: str) -> str:
        return "[image]"

    def count_tokens(self, text: str, *, for_vision: bool = False) -> int:
        return max(1, len(text) // 4)


@pytest.mark.asyncio
async def test_ingest_routes_mp3_to_audio_path(tmp_path: Path) -> None:
    from kagura_memory.ingest import FileIngestor

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")

    client = _make_client()
    ingestor = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    counter = {"n": 0}
    captured: list[dict[str, Any]] = []

    async def capture_remember(*, context_id: str, **kwargs: Any) -> dict[str, Any]:
        captured.append({"context_id": context_id, **kwargs})
        counter["n"] += 1
        return {"memory_id": f"mem-{counter['n']}"}

    mod = _mock_litellm(_Response(_GOOD_JSON, prompt=5000, completion=400))
    with (
        patch.object(_audio, "_load_litellm", return_value=mod),
        patch.object(client, "remember", side_effect=capture_remember),
    ):
        result = await ingestor.ingest(str(audio_file), context_id="ctx-uuid")

    assert result.success is True
    assert result.overview_id == "mem-1"
    assert len(result.section_ids) == 3
    # format label routed as audio; cost carries the provider token usage.
    assert captured[0]["details"]["format"] == "audio"
    assert result.cost.prompt_tokens == 5000
    assert result.cost.completion_tokens == 400
    assert result.cost.is_estimate is False

    await client.close()


@pytest.mark.asyncio
async def test_ingest_audio_transcription_failure_records_extract_error(tmp_path: Path) -> None:
    from kagura_memory.ingest import FileIngestor

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")

    client = _make_client()
    ingestor = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    mod = _mock_litellm([_Response("not json"), _Response("still not json")])
    with patch.object(_audio, "_load_litellm", return_value=mod):
        result = await ingestor.ingest(str(audio_file), context_id="ctx-uuid")

    assert result.success is False
    assert result.errors
    assert result.errors[0].step == "extract"
    await client.close()


@pytest.mark.asyncio
async def test_dry_run_audio_does_not_call_provider(tmp_path: Path) -> None:
    from kagura_memory.ingest import FileIngestor

    audio_file = tmp_path / "talk.mp3"
    audio_file.write_bytes(b"ID3\x04\x00fakeaudiobytes")

    client = _make_client()
    ingestor = FileIngestor(client=client, text_provider=_FakeProvider(), vision_provider=None)

    mod = _mock_litellm(_Response(_GOOD_JSON))
    with patch.object(_audio, "_load_litellm", return_value=mod):
        result = await ingestor.estimate_cost(str(audio_file))

    assert result.is_dry_run is True
    assert result.cost.is_estimate is True
    mod.acompletion.assert_not_called()  # NO network on dry-run
    assert any("estimate" in w for w in result.warnings)
    await client.close()


# ---------------------------------------------------------------------------
# Integration (default-skipped) — real Gemini transcription
# ---------------------------------------------------------------------------


@pytest.mark.audio
@pytest.mark.asyncio
async def test_real_gemini_transcription() -> None:
    """Requires GEMINI_API_KEY + network. Run with: pytest -m audio."""
    if not os.environ.get("GEMINI_API_KEY"):
        pytest.skip("GEMINI_API_KEY not set")
    fixture = Path(__file__).parent / "fixtures" / "sample.mp3"
    if not fixture.exists():
        pytest.skip("tests/fixtures/sample.mp3 not present")

    content, usage = await transcribe_audio(
        fixture.read_bytes(), mime="audio/mpeg", source_uri=str(fixture)
    )
    assert content.sections
    assert usage.prompt_tokens > 0


def test_audio_usage_defaults() -> None:
    u = AudioUsage()
    assert u.prompt_tokens == 0
    assert u.completion_tokens == 0
    assert u.model is None
