"""Kagura Memory SDK - AI-driven memory management for Kagura Memory Cloud."""

from .agent import KaguraAgent
from .client import MIN_SERVER_VERSION, KaguraClient
from .exceptions import (
    KaguraAuthError,
    KaguraConnectionError,
    KaguraContextError,
    KaguraError,
    KaguraLLMError,
    KaguraNotFoundError,
    KaguraQuotaError,
    KaguraRateLimitError,
)
from .models import (
    Artifact,
    ContextDetail,
    ContextInfo,
    ContextStats,
    DuplicateMemoryInfo,
    DuplicatePair,
    DuplicatesResponse,
    EmbeddingModel,
    EmbeddingModelsResponse,
    EmbeddingStatus,
    ExploredMemory,
    FailedMemoryInfo,
    FieldDefinition,
    LLMUsage,
    Memory,
    MemoryInfo,
    MemoryStatItem,
    MemoryStatsResponse,
    MemoryToStore,
    Message,
    PaginatedResourceTokensResponse,
    ProcessResult,
    RecallQuery,
    ResourceEventBatchRequest,
    ResourceEventBatchResponse,
    ResourceEventRequest,
    ResourceEventResponse,
    ResourceImpactResponse,
    ResourceSchemaResponse,
    ResourceTokenCreate,
    ResourceTokenCreateResponse,
    ResourceTokenResponse,
    ResourceTokenUpdate,
    SearchConfig,
    ServerFeatures,
    ServerInfo,
    Session,
    UsageInfo,
    UsageQuota,
    UsageQuotaLimitOnly,
    WorkspaceInfo,
)
from .resource_client import ResourceClient

__version__ = "0.11.0"

__all__ = [
    # Core classes
    "KaguraAgent",
    "KaguraClient",
    "ResourceClient",
    "MIN_SERVER_VERSION",
    # Embedding models
    "EmbeddingModel",
    "EmbeddingModelsResponse",
    # Models
    "Session",
    "Message",
    "Artifact",
    "ProcessResult",
    "Memory",
    "MemoryInfo",
    "MemoryToStore",
    "RecallQuery",
    "ExploredMemory",
    "LLMUsage",
    # Usage & context info (v0.6.1)
    "UsageInfo",
    "UsageQuota",
    "UsageQuotaLimitOnly",
    "SearchConfig",
    "ContextDetail",
    "WorkspaceInfo",
    "ContextStats",
    "ContextInfo",
    # Server info (v0.6.1)
    "ServerInfo",
    "ServerFeatures",
    # Embedding status (v0.6.1)
    "EmbeddingStatus",
    "FailedMemoryInfo",
    # Memory stats & duplicates (v0.6.1)
    "MemoryStatItem",
    "MemoryStatsResponse",
    "DuplicateMemoryInfo",
    "DuplicatePair",
    "DuplicatesResponse",
    # Resource Token models
    "ResourceTokenCreate",
    "ResourceTokenUpdate",
    "ResourceTokenResponse",
    "ResourceTokenCreateResponse",
    "PaginatedResourceTokensResponse",
    "ResourceEventRequest",
    "ResourceEventResponse",
    "ResourceEventBatchRequest",
    "ResourceEventBatchResponse",
    "ResourceImpactResponse",
    "FieldDefinition",
    "ResourceSchemaResponse",
    # Exceptions
    "KaguraError",
    "KaguraAuthError",
    "KaguraConnectionError",
    "KaguraRateLimitError",
    "KaguraNotFoundError",
    "KaguraQuotaError",
    "KaguraLLMError",
    "KaguraContextError",
]
