"""Kagura Memory SDK - AI-driven memory management for Kagura Memory Cloud."""

from .agents_client import AgentsClient
from .client import MIN_SERVER_VERSION, KaguraClient
from .exceptions import (
    KaguraAuthDeniedError,
    KaguraAuthError,
    KaguraAuthExpiredError,
    KaguraConnectionError,
    KaguraContextError,
    KaguraError,
    KaguraFeatureNotAvailableError,
    KaguraFetchError,
    KaguraIngestError,
    KaguraIntegrityError,
    KaguraLLMError,
    KaguraNotFoundError,
    KaguraPartialRollbackError,
    KaguraQuotaError,
    KaguraRateLimitError,
    KaguraResponseError,
)
from .files_client import FilesClient
from .ingest import FileIngestor
from .memory_client import MemoryClient
from .models import (
    GUARDRAIL_FORMAT,
    Agent,
    AgentBinding,
    AgentBootstrapAgent,
    AgentBootstrapBinding,
    AgentBootstrapComponentName,
    AgentBootstrapCorrelation,
    AgentBootstrapResponse,
    ContextDetail,
    ContextGuardrailItem,
    ContextGuardrails,
    ContextInfo,
    ContextStats,
    CostBreakdown,
    DuplicateMemoryInfo,
    DuplicatePair,
    DuplicatesResponse,
    Edge,
    EmbeddingModel,
    EmbeddingModelsResponse,
    EmbeddingStatus,
    FailedMemoryInfo,
    FieldDefinition,
    FileListResponse,
    FileObject,
    GuardrailDigest,
    GuardrailDigestTarget,
    GuardrailItem,
    GuardrailSet,
    IndexerJobStatus,
    IndexerSkippedReason,
    IndexerState,
    IndexerStateMetrics,
    IndexerStatusResponse,
    IngestErrorRecord,
    IngestResult,
    ListTagsResponse,
    MeasurementAggregate,
    MeasurementPeriod,
    MeasurementResult,
    MeasurementSeries,
    MemberAPIKey,
    MemoryListItem,
    MemoryListItemLocation,
    MemoryListResponse,
    MemoryStatItem,
    MemoryStatsResponse,
    PaginatedResourceTokensResponse,
    ResourceEventBatchRequest,
    ResourceEventBatchResponse,
    ResourceEventItem,
    ResourceEventRecord,
    ResourceEventRequest,
    ResourceEventResponse,
    ResourceEventsListResponse,
    ResourceImpactResponse,
    ResourceListItem,
    ResourceListResponse,
    ResourceSchemaResponse,
    ResourceSetupResponse,
    ResourceTokenCreate,
    ResourceTokenCreateResponse,
    ResourceTokenResponse,
    ResourceTokenUpdate,
    RollbackResult,
    RollbackSummary,
    SearchConfig,
    SeriesBucket,
    ServerFeatures,
    ServerInfo,
    SleepAction,
    SleepReport,
    SleepReportDetail,
    SleepRunStatus,
    TagInfo,
    ToolTrigger,
    UsageInfo,
    UsageQuota,
    UsageQuotaLimitOnly,
    WorkspaceInfo,
    WorkspaceInvitation,
    WorkspaceMember,
)
from .resource_client import ResourceClient
from .workspace_client import WorkspaceClient

__version__ = "0.42.0"

__all__ = [
    # Core classes
    "KaguraClient",
    "ResourceClient",
    "FilesClient",
    "WorkspaceClient",
    "AgentsClient",
    "MemoryClient",
    "MIN_SERVER_VERSION",
    # Embedding models
    "EmbeddingModel",
    "EmbeddingModelsResponse",
    # Usage & context info (v0.6.1)
    "UsageInfo",
    "UsageQuota",
    "UsageQuotaLimitOnly",
    "SearchConfig",
    "ContextDetail",
    "WorkspaceInfo",
    "ContextStats",
    "ContextInfo",
    # Server info (v0.6.1)
    "ServerInfo",
    "ServerFeatures",
    # Embedding status (v0.6.1)
    "EmbeddingStatus",
    "FailedMemoryInfo",
    # Memory list (SDK issue #143; bbox + location #254, server v0.54.0+)
    "MemoryListItem",
    "MemoryListItemLocation",
    "MemoryListResponse",
    # Measurement lane — HOW-MUCH axis (#254, server v0.54.0+)
    "MeasurementPeriod",
    "MeasurementAggregate",
    "MeasurementResult",
    "MeasurementSeries",
    "SeriesBucket",
    # Memory stats & duplicates (v0.6.1)
    "MemoryStatItem",
    "MemoryStatsResponse",
    "DuplicateMemoryInfo",
    "DuplicatePair",
    "DuplicatesResponse",
    # Edge model
    "Edge",
    # Tag vocabulary (server v0.15.4+)
    "TagInfo",
    "ListTagsResponse",
    # Resource Token models
    "ResourceTokenCreate",
    "ResourceTokenUpdate",
    "ResourceTokenResponse",
    "ResourceTokenCreateResponse",
    "PaginatedResourceTokensResponse",
    "ResourceEventRequest",
    "ResourceEventResponse",
    "ResourceEventBatchRequest",
    "ResourceEventBatchResponse",
    "ResourceEventRecord",
    "ResourceEventsListResponse",
    "ResourceImpactResponse",
    "FieldDefinition",
    "ResourceSchemaResponse",
    "ResourceSetupResponse",
    # Resource list (server v0.14+)
    "ResourceListItem",
    "ResourceListResponse",
    # Indexer status (server v0.14+)
    "IndexerJobStatus",
    "IndexerSkippedReason",
    "IndexerStateMetrics",
    "IndexerState",
    "ResourceEventItem",
    "IndexerStatusResponse",
    # File objects (server v0.15.1+)
    "FileObject",
    "FileListResponse",
    # Workspace member management (#225, server v0.42.0+)
    "WorkspaceMember",
    "WorkspaceInvitation",
    "MemberAPIKey",
    # Agent registry + bindings (#235, server v0.49.0+)
    "Agent",
    "AgentBinding",
    # Agent bootstrap (#231, server v0.49.0+)
    "AgentBootstrapAgent",
    "AgentBootstrapBinding",
    "AgentBootstrapComponentName",
    "AgentBootstrapCorrelation",
    "AgentBootstrapResponse",
    # Tool guardrails (#253, server v0.74.0+)
    "ToolTrigger",
    "GuardrailItem",
    "GuardrailSet",
    "GUARDRAIL_FORMAT",
    "GuardrailDigest",
    "GuardrailDigestTarget",
    "ContextGuardrails",
    "ContextGuardrailItem",
    # File ingestion (Issue #80)
    "FileIngestor",
    "IngestResult",
    "IngestErrorRecord",
    "CostBreakdown",
    # Sleep Maintenance (server v0.8+)
    "SleepRunStatus",
    "SleepReport",
    "SleepReportDetail",
    "SleepAction",
    "RollbackSummary",
    "RollbackResult",
    # Exceptions
    "KaguraError",
    "KaguraAuthError",
    "KaguraAuthExpiredError",
    "KaguraAuthDeniedError",
    "KaguraConnectionError",
    "KaguraRateLimitError",
    "KaguraNotFoundError",
    "KaguraResponseError",
    "KaguraQuotaError",
    "KaguraFeatureNotAvailableError",
    "KaguraPartialRollbackError",
    "KaguraLLMError",
    "KaguraContextError",
    "KaguraIntegrityError",
    "KaguraFetchError",
    "KaguraIngestError",
]
