"""Kagura Memory SDK - AI-driven memory management for Kagura Memory Cloud."""

from .agent import KaguraAgent
from .client import MIN_SERVER_VERSION, KaguraClient
from .exceptions import (
    KaguraAuthDeniedError,
    KaguraAuthError,
    KaguraAuthExpiredError,
    KaguraConnectionError,
    KaguraContextError,
    KaguraError,
    KaguraFetchError,
    KaguraIngestError,
    KaguraIntegrityError,
    KaguraLLMError,
    KaguraNotFoundError,
    KaguraQuotaError,
    KaguraRateLimitError,
)
from .files_client import FilesClient
from .ingest import FileIngestor
from .models import (
    Artifact,
    ContextDetail,
    ContextInfo,
    ContextStats,
    CostBreakdown,
    DuplicateMemoryInfo,
    DuplicatePair,
    DuplicatesResponse,
    Edge,
    EmbeddingModel,
    EmbeddingModelsResponse,
    EmbeddingStatus,
    ExploredMemory,
    FailedMemoryInfo,
    FieldDefinition,
    FileListResponse,
    FileObject,
    IndexerJobStatus,
    IndexerSkippedReason,
    IndexerState,
    IndexerStateMetrics,
    IndexerStatusResponse,
    IngestErrorRecord,
    IngestResult,
    ListTagsResponse,
    LLMUsage,
    Memory,
    MemoryInfo,
    MemoryListItem,
    MemoryListResponse,
    MemoryStatItem,
    MemoryStatsResponse,
    MemoryToStore,
    Message,
    PaginatedResourceTokensResponse,
    ProcessResult,
    RecallQuery,
    ResourceEventBatchRequest,
    ResourceEventBatchResponse,
    ResourceEventItem,
    ResourceEventRequest,
    ResourceEventResponse,
    ResourceImpactResponse,
    ResourceListItem,
    ResourceListResponse,
    ResourceSchemaResponse,
    ResourceSetupResponse,
    ResourceTokenCreate,
    ResourceTokenCreateResponse,
    ResourceTokenResponse,
    ResourceTokenUpdate,
    RollbackResult,
    RollbackSummary,
    SearchConfig,
    ServerFeatures,
    ServerInfo,
    Session,
    SleepAction,
    SleepReport,
    SleepReportDetail,
    SleepRunStatus,
    TagInfo,
    UsageInfo,
    UsageQuota,
    UsageQuotaLimitOnly,
    WorkspaceInfo,
)
from .resource_client import ResourceClient

__version__ = "0.21.0"

__all__ = [
    # Core classes
    "KaguraAgent",
    "KaguraClient",
    "ResourceClient",
    "FilesClient",
    "MIN_SERVER_VERSION",
    # Embedding models
    "EmbeddingModel",
    "EmbeddingModelsResponse",
    # Models
    "Session",
    "Message",
    "Artifact",
    "ProcessResult",
    "Memory",
    "MemoryInfo",
    "MemoryToStore",
    "RecallQuery",
    "ExploredMemory",
    "LLMUsage",
    # Usage & context info (v0.6.1)
    "UsageInfo",
    "UsageQuota",
    "UsageQuotaLimitOnly",
    "SearchConfig",
    "ContextDetail",
    "WorkspaceInfo",
    "ContextStats",
    "ContextInfo",
    # Server info (v0.6.1)
    "ServerInfo",
    "ServerFeatures",
    # Embedding status (v0.6.1)
    "EmbeddingStatus",
    "FailedMemoryInfo",
    # Memory list (SDK issue #143)
    "MemoryListItem",
    "MemoryListResponse",
    # Memory stats & duplicates (v0.6.1)
    "MemoryStatItem",
    "MemoryStatsResponse",
    "DuplicateMemoryInfo",
    "DuplicatePair",
    "DuplicatesResponse",
    # Edge model
    "Edge",
    # Tag vocabulary (server v0.15.4+)
    "TagInfo",
    "ListTagsResponse",
    # Resource Token models
    "ResourceTokenCreate",
    "ResourceTokenUpdate",
    "ResourceTokenResponse",
    "ResourceTokenCreateResponse",
    "PaginatedResourceTokensResponse",
    "ResourceEventRequest",
    "ResourceEventResponse",
    "ResourceEventBatchRequest",
    "ResourceEventBatchResponse",
    "ResourceImpactResponse",
    "FieldDefinition",
    "ResourceSchemaResponse",
    "ResourceSetupResponse",
    # Resource list (server v0.14+)
    "ResourceListItem",
    "ResourceListResponse",
    # Indexer status (server v0.14+)
    "IndexerJobStatus",
    "IndexerSkippedReason",
    "IndexerStateMetrics",
    "IndexerState",
    "ResourceEventItem",
    "IndexerStatusResponse",
    # File objects (server v0.15.1+)
    "FileObject",
    "FileListResponse",
    # File ingestion (Issue #80)
    "FileIngestor",
    "IngestResult",
    "IngestErrorRecord",
    "CostBreakdown",
    # Sleep Maintenance (server v0.8+)
    "SleepRunStatus",
    "SleepReport",
    "SleepReportDetail",
    "SleepAction",
    "RollbackSummary",
    "RollbackResult",
    # Exceptions
    "KaguraError",
    "KaguraAuthError",
    "KaguraAuthExpiredError",
    "KaguraAuthDeniedError",
    "KaguraConnectionError",
    "KaguraRateLimitError",
    "KaguraNotFoundError",
    "KaguraQuotaError",
    "KaguraLLMError",
    "KaguraContextError",
    "KaguraIntegrityError",
    "KaguraFetchError",
    "KaguraIngestError",
]
